Add yandex images as image identification option
vichan-devel/vichan pull request #430
Opened 2021-03-27 18:08 UTC by haruhianon609

**NOTE: This is compiltely untested!** I suggest that someone tests that this works before merging the PR.

2021-03-31 01:21 UTC, 27chan commented
The best way to use Yandex reverse search is to use it like this.

`<a rel="noreferrer" href="https://yandex.com/images/search?url={{ config.domain }}{{ config.uri_img }}{{ file.file }}&rpt=imagelike" target="_blank">Yandex</a>`

So we can find similar images, I use it in [bazukachan](https://github.com/27chan/bazukachan) and I have no problems besides having better results.

2021-03-31 05:37 UTC, haruhianon609 commented
ok, modified

2022-08-20 16:24 UTC, ctrlcctrlv requested changes

2022-08-20 16:24 UTC, ctrlcctrlv commented on templates/post/image_identification.html
> +                {% endif %}
Fix indentation.

2022-08-29 14:37 UTC, ctrlcctrlv commented on templates/post/image_identification.html
> +                {% endif %}
Did it for you.

2022-08-29 14:37 UTC, merged